apiVersion: v1
kind: Template
labels:
  template: sample-test
message: Creating a sample app
metadata:
  name: sample-test
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Sample APP
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${APPLICATION_NAME}:${IMAGE_VERSION_TAG}'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'php:7.3'
    postCommit: {}
    source:
      type: Git
      git:
        uri: '${GIT_REPO}'
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
- description: The name space for the application.
  displayName: Name Space
  name: NAMESPACE
  required: true
  value: test-1
- description: Namespace into which the PIE AMQ is to be deployed. 
  displayName: ImageStream Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
- description: Version of the PIE AMQ image.
  displayName: Image version
  name: IMAGE_VERSION_TAG
  required: true
- name: NBR_OF_PODS
  displayName: Number of instances
  description: The number of service instance (i.e. replicas).
  value: '1'
  required: true
- name: GIT_REPO
  displayName: Number of instances
  description: The number of service instance (i.e. replicas).
  value: '1'
  required: https://github.com/sclorg/cakephp-ex
   
